### ISSUE TITLE
Oraxen prefix doesn't seem to work under chance amount

### ISSUE THREAD

**Issue by goflishMC** [magemonkeystudio/mirage#34]
I set 50/50 chance for either iron ore or my oraxen silver ore to replace the break-material. However, it always comes back as iron ore.

I did a test with iron ore and diamond ore both having 50/50 chance and it worked just fine.

This is the error comes up about this in the latest.log: https://paste.travja.dev/sejuqifosu.md

<pre>
- material: IRON_ORE
  break-material: CRACKED_STONE_BRICKS
  #delay is in ticks (20=1s)
  regen-delay: 60
  tool:
    allowed:
    - minerspickaxe
    message: "You need a pickaxe tool to mine ores!"
    damage: 1
  chance:
    IRON_ORE: 0.5
    ORAXEN_SILVER_ORE: 0.5
  cancel-drop: true
  command:
  - delay: 0
    as: CONSOLE
    cmd: drops drop {player} ironnode
</pre>

**Comment by Travja** [comment]
I think this is actually working as it is supposed to. Some sort of configuration issue here. 🤷🏻‍♂️
